name: python-flask app deployment

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'subdir/package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
    - name: Clear contents of /var/www/html
      run: sudo rm -rf /var/www/html/*
    - name: Copy dist folder to /var/www/html
      run: sudo cp -r dist/* /var/www/html
      
  deploy:
    runs-on: ubuntu-latest
    name: deployment on EC2 instance

    steps:
      - name: Checkout the files to github runner
        uses: actions/checkout@v2

      - name: Deploy backend
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_IP_ADDRESS }}
          REMOTE_USER: ${{ secrets.EC2_USERNAME }}
        run: | 
          echo "$SSH_PRIVATE_KEY" > private_key_ec2.pem && chmod 600 private_key_ec2.pem
          ssh -o StrictHostKeyChecking=no -i private_key_ec2.pem ${REMOTE_USER}@${REMOTE_HOST} '
          echo "Current directory: $(pwd)"
          echo "Listing home directory:"
          ls -la ~
          source ~/.bashrc          
          pkill python3
          cd /home/ubuntu/chat-app-flask-react/backend
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          nohup python3 -m src > log.txt 2>&1 &
          '